package: treestructure
version: '1.0 beta'
author: Thomas Goellner
supportpage: www.redaxo.org/de/forum/

page:
    title: translate:title
    perm: treestructure[]
    pjax: true

requires:
    packages:
        structure: '^2.0.0'
    redaxo: '>=5.0.0-beta2'
